default: &default
  partners:
    chancen-ke:
      name: Chancen Kenya
      type: financial
      metadata:
        required:
          - key
          - name
          - type
        defaults:
          key: chancen-ke
          name: Chancen Kenya
          type: financial
          country: KE
          currency: KES
          date_format: "%d/%m/%Y"
          locale: en
          pei_array: []
          vector_store_id_array: ["vs_68df09dd7b2c819180c8e6b7ac3acbe2"]
          bank_array: ["Choice Bank"]
          ui_layout: intro
          ai_enabled: true
      onboarding:   # TODO: implement in onboarding navigation partials
        default:
          - setup
          - preferences
          - goals
          - trial
        steps:
          - goals
    chancen-rw:
      name: Chancen Rwanda
      type: financial
      metadata:
        required:
          - key
          - name
          - type
        defaults:
          key: chancen-rw
          name: Chancen Rwanda
          type: financial
          country: rw
          pei_array: []
          vector_store_id_array: []
          bank_array: ["Equity Bank"]
          ui_layout: intro
          ai_enabled: true
      onboarding:   # TODO: implement in onboarding navigation partials
        default:
          - setup
          - preferences
          - goals
          - trial
        steps:
          - setup
          - preferences
          - kyc   # TODO: implement KYC flow that is partner-specific (manual in Rwanda?)
          - goals
          - trial
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
